### ISSUE TITLE
Disabling STIG-IDs

### ISSUE THREAD

**Issue by jasoncal108** [ansible/ansible-lockdown#12]
Hi,
 I want to disable STIG-IDs in defaults/main.yml as some are not functional within AWS such as the bootstrap password (RHEL-07-010480, RHEL-07-010490). The only method i found is by commenting out both the STIG-ID in 'defaults/main.yml' and also within tasks/fix-cat1.yml comment out these tasks. Is there any easier way to do this? 

```
#- name: |
#
#      "HIGH | RHEL-07-010480 | PATCH | Systems with a Basic Input/Output System (BIOS) must require authentication upon booting into single-user and maintenance modes."
#      "HIGH | RHEL-07-010490 | PATCH | Systems using Unified Extensible Firmware Interface (UEFI) must require authentication upon booting into single-user and maintenance modes."
#  lineinfile:
#      dest: /etc/grub.d/40_custom
#      insertafter: EOF
#      regexp: "{{ item.regexp }}"
#      line: "{{ item.line }}"
#  with_items: "{{ rhel7stig_boot_password_config }}"
#  notify: make grub2 config
#  when: rhel_07_010480 or rhel_07_010490
#  tags:
#      - cat1
#      - high
#      - patch
#      - RHEL-07-010480
#      - RHEL-07-010490
#      - grub
#      - bootloader
```

**Comment by samdoran** [comment]
Yes. We're moving to adding variables for each finding ID in addition to tags. This will let you disable findings individually and save that as a variable in a file.
