### ISSUE TITLE
WIP Merger with OpenStack's Ansible Hardening

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible-lockdown#16]
Document effort to merge projects.

### First Meeting

**Minutes** https://meetbot.fedoraproject.org/ansible-lockdown/2018-10-17/hardening-lockdown_merger_first_steps.2018-10-17-14.04.html
**Logs** https://freenode.logbot.info/ansible-lockdown/20181017

To Do's
- [ ] Migrate docs to AH based sphinx generation. Each repo to have sphinx docs that are ultimately aggregated into a single build to publish a unified docs site
- [ ] Make tests be driven by Zuul to leverage OpenStacks infra
- [ ] Create an 'extras' task file to include extra hardening tasks that arent a part of the STIG standard to maintain backward compatibility with Ansible Hardening

**Comment by juliedavila** [comment]
cc @jamescassell @shepdelacreme

**Comment by codrcodz** [comment]
Glad to see you guys collaborating on this!

**Comment by shepdelacreme** [comment]
For the documentation it looks like it would be pretty easy to add a top level doc builder to this repo that uses `toctree` to reference the docs folders in git submodules. I'm going to start working on migrating the AH docs builder into the RHEL7-STIG repo and then we should be able to add a basic sphinx config/builder to this repo to see what it works/looks.

**Comment by juliedavila** [comment]
@shepdelacreme could you do that on a branch? (if you arent already)

**Comment by shepdelacreme** [comment]
Yup I was planning on starting a new branch over at the RHEL7-STIG repo. Once those docs are done we can start on the top level stuff in a branch in this repo.

**Comment by gundalow** [comment]
Hey folks
The Ansible Lockdown project has moved to https://github.com/orgs/ansible-lockdown/repositories

So have a look at the stuff that's happening there.

To chat with the community, join our [Discord Server](https://discord.io/ansible-lockdown) to ask questions, discuss features, or just chat with other Ansible-Lockdown users.

Therefor I'm closing this and archiving (making readonly) https://github.com/ansible/ansible-lockdown
