### ISSUE TITLE
Update from latest repositories.

### ISSUE THREAD

**Issue by dfederlein** [ansible/ansible-lockdown#17]
While a new collection is imminent, this repo is woefully out of date with the community:

https://github.com/ansible-lockdown

**Comment by gundalow** [comment]
Hey folks
The Ansible Lockdown project has moved to https://github.com/orgs/ansible-lockdown/repositories

So have a look at the stuff that's happening there.

To chat with the community, join our [Discord Server](https://discord.io/ansible-lockdown) to ask questions, discuss features, or just chat with other Ansible-Lockdown users.

Therefor I'm closing this and archiving (making readonly) https://github.com/ansible/ansible-lockdown
