### ISSUE TITLE
Package as collection and upload to ansible galaxy

### ISSUE THREAD

**Issue by db0** [ansible/ansible-lockdown#18]
Ansible Collections is the optimal way to share content such as this role with the community. 

Therefore, it would be good to bundle the roles provided in the ansible-lockdown umbrella into a collection.

**Comment by gundalow** [comment]
Hey folks
The Ansible Lockdown project has moved to https://github.com/orgs/ansible-lockdown/repositories

So have a look at the stuff that's happening there.

To chat with the community, join our [Discord Server](https://discord.io/ansible-lockdown) to ask questions, discuss features, or just chat with other Ansible-Lockdown users.

Therefor I'm closing this and archiving (making readonly) https://github.com/ansible/ansible-lockdown
