### ISSUE TITLE
Please update the RHEL6-STIG sub-module location

### ISSUE THREAD

**Issue by Dan0maN** [ansible/ansible-lockdown#9]
When I perform a clone of the repository with --recursive, the clone fails to pull the RHEL6-STIG due to the URL of the sub-module being SSH vs HTTPS.  Users behind a proxy (like myself) may not be able to reach this URL.

Please update the RHEL6-STIG sub-module location from
<code>git@github.com:MindPointGroup/RHEL6-STIG.git</code>
to
<code>https://github.com/MindPointGroup/RHEL6-STIG.git</code>

**Comment by samdoran** [comment]
I updated the submodule to use the HTTPS URL. Thanks for pointing this out!

**Comment by Dan0maN** [comment]
Thanks for being open to clear it up!
